### ISSUE TITLE
Listar possíveis locais para a realização do evento

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#1]
Issue para listar e descrever possíveis locais para a realização do evento

**Adicionar aqui na descrição algo como "o que queremos no local do evento"...**
Quantidade esperada de pessoas?
Data?
Precisa ter quantas salas com projecao e capacidade para dividir todas as pessoas do evento?
Precisa ter uma sala principal que comporte todas as pessoas do evento

**Comment by renan-assis-santos** [comment]
[Centro Cultural São Paulo](https://centrocultural.sp.gov.br/espacos/)

Possui 5 salas de espetáculos, cada um com suas especificações. Além disso, possuem dois pisos expositivos que abrigariam mostras ou exposições que gostaríamos de fazer, além de ser espaços de permanência comum entre atividades. A maior sala (Adoniran Barbosa) possui capacidade para 551 pessoas, incluindo pisos superior e inferior, além de ser uma sala "circular" onde as pessoas estão acomodadas ao redor do palco, vide imagem abaixo.
![Image](https://github.com/pythonbrasil/pybr2025-org/assets/61845573/28512613-31e1-4696-aec6-29771ccdb327)
As outras salas possuem capacidade para 330 pessoas (Jardel Filho), 200 pessoas (Paulo Emílio) e 200 pessoas (Ademar Guerra).

Pelos principais motivos da maior sala comportar apenas 551 pessoas e ser "circular", esse local não seria viável para realizar a Python Brasil 2025

**Comment by renan-assis-santos** [comment]
Abaixo temos outras sugestões de locais dadas na última reunião do dia 13/03 que precisamos nos aprofundar:

- Biblioteca Mario de Andrade (Cryptorave vai ser lá)
- Memorial da america latina
- IMS Paulista (Instituto Moreira Salles)
- [Sao Luís Eventos](https://saoluiseventos.com.br/#home)
- USP Cidade Universitária (ver centro de convencoes, IME, etc)
- [Centro de Convenções Rebouças](https://convencoesreboucas.com.br/ccr/portal/)

**Comment by belaaiza** [comment]
**Quantidade esperada de pessoas?** 1000
**Data?** Outubro
**Precisa ter quantas salas com projecao e capacidade para dividir todas as pessoas do evento?**
1 auditório para keynote e 3 salas para as trilhas

**Comment by belaaiza** [comment]
TO DO: Orçar quanto ficaria para usarmos salões com equipamento pra audição dos áudios ao invés de salas separadas

**Comment by renan-assis-santos** [comment]
Enviei email para primeiro contato com os seguintes locais:
* [Sao Luís Eventos](https://saoluiseventos.com.br/#home)
* [Centro de Convenções Rebouças](https://convencoesreboucas.com.br/ccr/portal/) (TDC 2024 foi aqui)
* [Amcham](https://www.amcham.com.br/index/business-center) - PythonBrasil 2011 foi lá
* [Centro de convenções Frei Caneca](https://www.convencoesfreicaneca.com.br/)
* Centro de Eventos ProMagno
* Distrito Anhembi

**Comment by renan-asantos** [comment]
Adicionei todos os locais e o status de cada um nessa [planilha](https://docs.google.com/spreadsheets/d/1V3VS9xaWxeR7xKeugC-4g3VNBGD8BO-2rAfVpqGnjOs/edit?usp=drive_link) do nosso drive.
Todas as informações de cada local cotado estão nessa [pasta](https://drive.google.com/drive/u/0/folders/1xZ5UUOSpMVIVjWHB09dmuvKz0T1uvizg)

**Comment by renan-asantos** [comment]
Todos os possíveis locais pensados para realizar o evento já foram compilados na issue #8 
Assim, concluo essa issue
