### ISSUE TITLE
São Luis Eventos

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#20]

**Comment by belaaiza** [comment]
Renan entrou em contato mas a agenda de 2025 ainda estava fechada, entrei em contato de novo e agora abriu, vão responder nosso e-mail

**Comment by renan-asantos** [comment]
Responderam o email com a proposta e a planta do local, pareceu promissor. Adicionei os anexos mandados na pasta do drive e estamos analisando e questionando sobre a viabilidade.
O preço e local parecem viaveis com alguns ajustes

**Comment by renan-asantos** [comment]
Esse foi o local decidido para realizar a Python Brasil 2025 em São Paulo. Seguiremos com o contrato e formalização em outra issue
