### ISSUE TITLE
Centro de Convenções Rebouças

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#21]
O [centro de convenções rebouças](https://convencoesreboucas.com.br/ccr/portal/) é um espaço para eventos localizado na avenida consolação (próximo por 600m aos metrôs paulista e clínicas). 
Possui os seguintes espaços (PAX = Pessoas sentadas):

1. Auditórios:
 a. Vermelho (134 PAX)
 b. Turquesa (900 PAX)
 c. Amarelo (184 PAX)
 d. Grande auditório (555 PAX)
2. Sala turquesa 1 (90 PAX)
3. Sala turquesa 2 (160 PAX)
4. Sala turquesa 3 (160 PAX)
5. Sala turquesa 4 (90 PAX)
6. Sala turquesa 5 (160 PAX)
7. Sala turquesa 6 (160 PAX)
8. Sala branca (15 PAX)
9. Sala marrom (50 PAX)
10. Sala verde (50 PAX)
11. Sala havana (50 PAX)
12. Sala coral (70 PAX)
13. Salões de 100m2, 250m2, 415m2, 576m2 ou 850m2.

**Comment by belaaiza** [comment]
Rebouças disse que não encontrou nosso contato feito pelo site, pediram para reenviar para reboucas@hc.fm.usp.br

**Comment by renan-asantos** [comment]
Local decidido pelo Centro de Eventos São Luís #20
