### ISSUE TITLE
Centro de Convenções Frei Caneca

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#27]

**Comment by belaaiza** [comment]
Entrei em contato por telefone no dia 30/08, ficaram de responder nosso e-mail

**Comment by renan-asantos** [comment]
Comentaram que possuem bloqueios de agenda em novembro que vão ver se se mantêm na semana que vem e disseram que entram em contato caso haja disponibilidade. Infelizmente, não tenho tantas esperanças visto a alta procura do local
