### ISSUE TITLE
Fechar contrato do local de evento

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#31]
Na issue #8 foi decidido o local de evento pelo Centro de Eventos São Luís. A partir dessa decisão precisamos fechar o contrato de locação.

A proposta de locação está nessa [pasta do drive](https://drive.google.com/drive/u/0/folders/1ciPdU5oOshcRfiRxWZJtbQu0NOj9e2V6)

O período será dividido em:
* Evento principal nos dias 24, 25 e 26/10/2025 das 08:00 as 18:00 horas
* Montagem no dia 23/10/2025 das 07:00 as 19:00 horas
* Desmontagem e devolução do espaço no dia 26/10/2025 após o evento até as 00:00 horas

O valor total da locação ficou em R$202.000

Foi decidida a opção de pagamento 10% na assinatura do contrato e 90% (noventa por cento) pago em duas vezes (o último pagamento deve ocorrer pelo menos 10 dias antes do evento)

**Comment by renan-asantos** [comment]
A Fabiana, responsável pelo São Luís, solicitou os dados abaixo para gerar o contrato de locação:
* Contrato social ou Estatuto Social
* Cartão CNPJ
* Procuração (se houver)
* RG, CPF e comprovante de residência do representante legal

Pedi para a diretoria da APyB e a Any(presidente da APyB) compartilhou comigo os documentos. Enviei por email para a Fabiana para o contrato de locação.

Ficamos no aguardo do contrato

**Comment by renan-asantos** [comment]
Preenchido e enviado [formulário](https://docs.google.com/forms/d/e/1FAIpQLSdtHD8t-P7dYqoCBonXOCv_WsHhmekZvulKOMHHJagxG1laSg/viewform) de cadastro do evento da APyB com meus dados como responsável pelo evento PythonBrasil 2025 (código pybr2025)

**Comment by renan-asantos** [comment]
Recebemos hoje por email o contrato de locação do Centro de Eventos São Luís, fiz upload dele no [drive](https://drive.google.com/file/d/1nAdCE69M5qjYYX2Qzb29KunIkoaHTTKT/view?usp=drive_link).
@cecivieira ainda vou ler o contrato com calma, mas a APyB possui alguém com experiência em revisar contratos caso precisemos de ajuda?

**Comment by renan-asantos** [comment]
Contrato lido, tiveram apenas algumas questões comentadas abaixo que mandei para a Fabiana (representante do São Luís) para entender melhor.

1. No quadro resumo, tópico 2, a palavra assistente está escrito errado como "asssitente"
2. No quadro resumo, tópico 4, está "Evento: 3 diária (s) - Data: 24 a 26 de outubro de 2025 - Horário: 08:00h às 18:00h"
É possível esses horários mudarem para um pouco antes começando 7h e terminar um pouco depois às 20h? Isso para ter a disponibilidade de arrumar algo faltante do evento antes das pessoas chegarem e depois do evento para caso atrase algo?
3. Na cláusula sexta paragrafo terceiro diz que não estão inclusas mesas, cadeiras e vários outros serviços, entretanto na proposta estava dizendo que incluía 531 cadeiras de plástico branco e 45 mesas redondas com 1,15 cm de diâmetro. Essas mesas e cadeiras estarão disponíveis caso precisemos usar?
4. As informações que solicitou no último email (representante legal e email) são para a assinatura do contrato da página 9, no campo da associação python brasil, que no caso seria a Anicely?
5. As informações de testemunha (nome completo, CPF e email) são para a assinatura da página 9 também, certo?
---

@anicelysantos @cecivieira tenho algumas dúvidas que gostaria de tirar:
1. Li o contrato e não vi nada errado ou que nos colocasse em risco na realização do evento, mas a APyB teria alguém com experiência em revisar contratos para dar uma segunda checagem?
2. O valor total do local é R$202.000, é necessário o pagamento de um sinal de 10% (R$20.200) na data 30/10 e o resto do pagamento bem próximo ao evento. Esse valor e data do sinal é viável com o caixa existente?
3. A forma de pagamento é por boleto, existe nota fiscal ou algo similar ao locar um espaço?
4. Precisa da assinatura da APyB no final do contrato, seria a Any certo? Além disso, precisa de uma testemunha, posso colocar eu mesmo?

**Comment by biancarosa** [comment]
Li a proposta e comparando com a desse ano e algumas dificuldades nossas, achei excelente conter o horário de montagem e entrega do salão.

Tb acho uma boa pedir para ter acesso ao local as 7am e até umas 21h nos outros dias.

Vi que segurança, recepção, portaria não tá incluso - eles tem alguém no prédio que faça isso e contrataremos ou é 100% por nossa conta?

Como é questão de acessibilidade: elevadores, rampas?

Achei excelente não ter venda casada de serviços :)

**Comment by renan-asantos** [comment]
> Li a proposta e comparando com a desse ano e algumas dificuldades nossas, achei excelente conter o horário de montagem e entrega do salão pós evento.
> 
> Tb acho uma boa pedir para ter acesso ao local as 7am e até umas 21h nos outros dias.
> 
> Vi que segurança, recepção, portaria não tá incluso - eles tem alguém no prédio que faça isso e contrataremos ou é 100% por nossa conta?
> 
> Como é questão de acessibilidade: elevadores, rampas?
> 
> Achei excelente não ter venda casada de serviços :) 

@biancarosa vocês tiveram algum problema com horários de montagem ou entrega?

É por nossa conta segurança, recepção etc. Existem seguranças do local, mas não ficam responsáveis nos locais do evento.

Sobre acessibilidade, em todo o percurso do público não existem outros andares. Em alguns cantos específicos tem uma escada com salinha pequena que pensamos usar de depósito ou sala da org, mas não é do público geral não.

**Comment by cecivieira** [comment]
> 1. Li o contrato e não vi nada errado ou que nos colocasse em risco na realização do evento, mas a APyB teria alguém com experiência em revisar contratos para dar uma segunda checagem?
Sim, temos um assessor jurídico, mas há um custo adicional. Verificarei o preço.

> 2. O valor total do local é R$202.000, é necessário o pagamento de um sinal de 10% (R$20.200) na data 30/10 e o resto do pagamento bem próximo ao evento. Esse valor e data do sinal é viável com o caixa existente?
Sim, esse valor é viável com o caixa existente.

> 3. A forma de pagamento é por boleto, existe nota fiscal ou algo similar ao locar um espaço?
Sim, o locla deve emitir uma nota fiscla no valor da parcela a ser paga. Nela deve ser informado os dados bancários.

> 4. Precisa da assinatura da APyB no final do contrato, seria a Any certo? Além disso, precisa de uma testemunha, posso colocar eu mesmo?
Sim, a assinatura deve ser sua e de Any

----

Adicionalmente às perguntas de Bia, eu só tenho a sugestão de correção do e-mail de contato no item I.3.
Reforço a pergunta sobre a cessionária disponibilizar equipe responsável pela infraestrutura do local, por exemplo, se a energia do prédio cair, quem resolve?
Não vi no contrato a citação de serviço de internet. Será necessário contratação de link dedicado?

**Comment by renan-asantos** [comment]
> Sim, temos um assessor jurídico, mas há um custo adicional. Verificarei o preço.
> Sim, esse valor é viável com o caixa existente.
> Sim, o locla deve emitir uma nota fiscla no valor da parcela a ser paga. Nela deve ser informado os dados bancários.
> Sim, a assinatura deve ser sua e de Any

Beleza, muito obrigado @cecivieira!

> Adicionalmente às perguntas de Bia, eu só tenho a sugestão de correção do e-mail de contato no item I.3. Reforço a pergunta sobre a cessionária disponibilizar equipe responsável pela infraestrutura do local, por exemplo, se a energia do prédio cair, quem resolve? Não vi no contrato a citação de serviço de internet. Será necessário contratação de link dedicado?

Tem razão, vou mandar pra corrigirem o email de contato sendo o eventos@python.org.br.
Sobre a equipe responsável, existe no contrato dizendo que eles possuem equipe para orientar, supervisionar e fiscalizar as atividades.
No exemplo da energia cair, no contrato diz que a Cedente é responsável pelo fornecimento de energia e agua durante todo o evento e um próximo paragrafo dizendo que "o regular fornecimento de energia e agua está por parte das concessionárias competentes (ENEL/SABESP)". Vou questionar sobre isso no email também e perguntar se existe geradores, pois não vi isso também.
Na parte 2.2 parágrafo terceiro tem dizendo que internet e vários outros serviços ficam de nossa responsabilidade.

**Comment by renan-asantos** [comment]
Atualizando aqui:

1. Eles não possuem geradores, precisaríamos contratar
2. Enviei os dados faltantes do Representante legal (Any) e Testemunha (eu).
3. Solicitei o “Termo de Vistoria Inicial” (“Anexo I") que é mencionado no tópico II, cláusula segunda, parágrafo primeiro, mas não se encontra no documento.
4. Eu @anadulce e @ericof tivemos uma reunião com o Bruno (advogado que presta serviços para a APyB) para fechar a revisão desse contrato e de outros futuros. Ele sugeriu para fazermos revisões avulsas com ele que seria melhor (para organização e financeiramente) do que fechar um pacote. Por fim, compartilhei com ele o contrato de locação para avaliar e fazer um orçamento de revisão.

**Comment by renan-asantos** [comment]
Fabiana respondeu que o Termo de Vistoria é um checklist de entrega e devolução do local, realizado pré e pós evento de segunda a sexta.
Comentei sobre possibilidade de fazermos essa vistoria semana que vem

**Comment by renan-asantos** [comment]
Foi respondido que o Termo de Vistoria é feito apenas 1 dia antes do início do evento para que eles entreguem as chaves para a gente.
Vou solicitar a alteração da data de pagamento do sinal para dia 14/11 para dar um tempo razoável do Bruno revisar o contrato e o pagamento pela APyB ser feito.

**Comment by anicelysantos** [comment]
@renan-asantos o contrato chegou pra assinatura aqui. Bruno já revisou?

**Comment by renan-asantos** [comment]
> @renan-asantos o contrato chegou pra assinatura aqui. Bruno já revisou?

@anicelysantos chegou aqui pra mim tbm, ele ainda não revisou não e tem coisa errada no contrato tbm. Vou mandar email comentando esses pontos

**Comment by anicelysantos** [comment]
Show! vou acompanhar :)

**Comment by renan-asantos** [comment]
O Bruno revisou o contrato de locação e colocou os pontos nesse [email do freshdesk](https://pythonbrasil.freshdesk.com/helpdesk/tickets/12070).
Respondi o email da Fabiana hoje de manhã sobre o contrato enviado para assinatura e que teríamos mais alguns comentários do Bruno e amanhã pretendo mandar o email pra ela pedindo o que foi solicitado e esclarecendo mais dúvidas do contrato.
cc @anicelysantos

**Comment by renan-asantos** [comment]
Mandei email para a Fabiana com todas as dúvidas que o Bruno comentou na análise do contrato.
Aguardando resposta

**Comment by renan-asantos** [comment]
Fabiana mandou email com todas as dúvidas respondidas e Bruno já deu ok no contrato.
---
@cecivieira @anicelysantos gostaria de tirar duas dúvidas
1. Receberam meu email sobre a questão do Sao Luis não emitir nota fiscal? Existe algum problema quanto a isso?
2. Se estiver tudo certo, posso colocar o pagamento da primeira parcela (R$20.200) para o dia 29/11?

**Comment by anadulce** [comment]
@anicelysantos e @cecivieira precisamos do parecer de vocês com urgência, pois estamos correndo o risco de perder o local. Infelizmente, não encontramos outras opções com as mesmas características e valores para uma possível substituição, por isso essa é uma questão crucial para o evento.

**Comment by tiidadavena** [comment]
> Receberam meu email sobre a questão do Sao Luis não emitir nota fiscal? Existe algum problema quanto a isso?

De acordo com a contadora, não há problema em eles emitirem apenas recibo, desde que haja o contrato assinado entre as duas partes.

> Se estiver tudo certo, posso colocar o pagamento da primeira parcela (R$20.200) para o dia 29/11?

Pode sim.

**Comment by renan-asantos** [comment]
@anicelysantos o pessoal do São Luis mandou o contrato com tudo corrigido, até a data de pagamento da primeira parcela que ficou para o dia 29/11.
Acabei de assinar, aí está disponível pra você assinar também

**Comment by anadulce** [comment]
@anicelysantos poderia assinar o contrato com o Bruno, relativo a consultoria jurídica contratada para revisar a locação do São Luis, por favor?
O pagamento está previsto para o dia 10 de dezembro neste caso.
Ele foi enviado para o e-mail da diretoria também.
https://drive.google.com/file/d/1AEJjENo-VO2S5bYNYEFS6OOSmGdug_eK/view?usp=sharing

**Comment by anicelysantos** [comment]
@anadulce aqui está: https://drive.google.com/file/d/1kkDkvXlHNwT3nP9puu-b-08Y62PQ_TWk/view?usp=drive_link
@renan-asantos não encontrei aqui. me manda o email de envio deles pra eu pesquisar na minha caixa de emails, por favor.

**Comment by anicelysantos** [comment]
@renan-asantos já encontrei, assinando agora!

**Comment by anicelysantos** [comment]
aaaah outra coisa:
@anadulce e @renan-asantos solicitem o formulário de solicitações de pagamento para estes pagamentos, por favor (caso não tenham feito ainda). :)

**Comment by renan-asantos** [comment]
> aaaah outra coisa: @anadulce e @renan-asantos solicitem o formulário de solicitações de pagamento para estes pagamentos, por favor (caso não tenham feito ainda). :)

Pode deixar, mandei email agora pedindo os dados para o pagamento sobre o local de evento. Quando responderem eu mando no formulário de solicitação de pagamento

**Comment by renan-asantos** [comment]
Responderam meu e-mail dizendo que vão enviar o boleto ainda

**Comment by renan-asantos** [comment]
Enviaram o boleto na segunda de manhã, mas não recebi notificação do freshdesk.
Vi agora quarta 15h e preenchi a solicitação de pagamento da APyB enviando os dados do fornecedor e boleto no valor de R$20.200.
**PONTO DE ATENCAO**: o vencimento do boleto é para essa **sexta-feira 29/11**
cc @anicelysantos @cecivieira @tiidadavena @naanadr

**Comment by renan-asantos** [comment]
Pagamento do boleto realizado no dia 29/11, contrato assinado e coloquei o zip com o PDF do contrato e das assinaturas no drive na pasta "contratos".
Isso finaliza essa issue.
Deixei de lembrete para mim, manter o lembrete de quando serão pagas as próximas parcelas
