### ISSUE TITLE
Iniciar rascunho do plano de patrocínio

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2025-org#39]

**Comment by belaaiza** [comment]
Uma primeira versão da tabela para colocarmos no plano: https://docs.google.com/spreadsheets/d/1EgCydCUlkLRKlw6CWftke-2av5hru9L7NzrAovmNnfQ/edit?pli=1&gid=381705089#gid=381705089

acham que podemos colocar as mídias impressas pra todos? ou talvez algumas repetições do vídeo no intervalo pré e pós almoço pro bronze, ele ficou sem nenhum benefício de expoisição de marca no evento

**Comment by belaaiza** [comment]
Alguns pontos que debatemos mas ficamos sem bater um martelo:

Um paragrafo sobre a empresa nas newsletter de comunicação com os participantes (mandar sempre em cada email de comunicacao com participantes) - debatemos que era pouco benefício pois enviamos poucos e-mails
Coleta de dados dos participantes através de QR Code - debatemos que era bom mas tinha o trabalho de gerar o QR Code, acho que vale a pena
Vinheta entre as palestras do evento - lembro que comentamos de não colocar esse, concordam?
Adicionar brindes ou produtos nas sacolas dos participantes - Ana comentou que seria encher linguiça pq as empresas já sabem que podem fazer isso, mas acham válido colocar pra informar empresas que estejam patrocinando a primeira vez?

**Comment by renan-asantos** [comment]
> Uma primeira versão da tabela para colocarmos no plano: https://docs.google.com/spreadsheets/d/1EgCydCUlkLRKlw6CWftke-2av5hru9L7NzrAovmNnfQ/edit?pli=1&gid=381705089#gid=381705089
> 
> acham que podemos colocar as mídias impressas pra todos? ou talvez algumas repetições do vídeo no intervalo pré e pós almoço pro bronze, ele ficou sem nenhum benefício de expoisição de marca no evento

As mídias impressas acho que da pra colocar pra todos sim, aí só mudarmos o layout pra ter mais destaque pra cotas maiores. Inicialmente pensei em não colocar as repeticoes do video pro bronze, mas ta bem pobrezinho de beneficio pra eles, acho que da pra colocar sim
Outras dúvidas:
1. Desconto em ingressos adicionais, isso seria referente ao preço do ingresso vigente na data certo?
2. Sobre os vídeos do intervalo pre e pós almoço, penso que tem muita repetição. Eu diminuiria pra 8, 6, 4 e 2 (contando com bronze)
---

> Alguns pontos que debatemos mas ficamos sem bater um martelo:
> 
> Um paragrafo sobre a empresa nas newsletter de comunicação com os participantes (mandar sempre em cada email de comunicacao com participantes) - debatemos que era pouco benefício pois enviamos poucos e-mails
Mesmo que seja poucos emails acho que vale sim, se a empresa n quiser só tirar, n é como se fosse um grande trabalho pra a gente tbm.

> Coleta de dados dos participantes através de QR Code - debatemos que era bom mas tinha o trabalho de gerar o QR Code, acho que vale a pena.
Acho que dá tbm, mas ouviria a opinião dos outros sobre

> Vinheta entre as palestras do evento - lembro que comentamos de não colocar esse, concordam?
É mto corrido o intervalo entre as palestras n vale colocar não.

>Adicionar brindes ou produtos nas sacolas dos participantes - Ana comentou que seria encher linguiça pq as empresas já sabem que podem fazer isso, mas acham válido colocar pra informar empresas que estejam patrocinando a primeira vez?
Acho válido colocar tbm, qualquer pessoa ficaria curiosa com os brindes nas sacolas, incentivar a ter isso acho uma boa

**Comment by renan-asantos** [comment]
Alias, outro ponto, o numero de ingressos cortesia por patrocinador tem alguma logica? 15, 7,4,3?

**Comment by anadulce** [comment]
@belaaiza @renan-asantos 
 > acham que podemos colocar as mídias impressas pra todos? ou talvez algumas repetições do vídeo no intervalo pré e pós almoço pro bronze, ele ficou sem nenhum benefício de expoisição de marca no evento
 
 > As mídias impressas acho que da pra colocar pra todos sim, aí só mudarmos o layout pra ter mais destaque pra cotas maiores. Inicialmente pensei em não colocar as repeticoes do video pro bronze, mas ta bem pobrezinho de beneficio pra eles, acho que da pra colocar sim

1 - Por mim, podemos tanto adicionar nas mídias impressas, respeitando as proporções, quanto nos vídeos.

> Um paragrafo sobre a empresa nas newsletter de comunicação com os participantes (mandar sempre em cada email de comunicacao com participantes) - debatemos que era pouco benefício pois enviamos poucos e-mails

> Mesmo que seja poucos emails acho que vale sim, se a empresa n quiser só tirar, n é como se fosse um grande trabalho pra a gente tbm.

2 - Acho que a questão dos e-mails pra mim só parece propaganda enganosa, porque como enviamos poucos, isso não vai ser um benefício real.

>  Coleta de dados dos participantes através de QR Code - debatemos que era bom mas tinha o trabalho de gerar o QR Code, acho que vale a pena

> Acho que dá tbm, mas ouviria a opinião dos outros sobre 

3 - Sou a favor do QRCode também;

>  Vinheta entre as palestras do evento - lembro que comentamos de não colocar esse, concordam?

> É mto corrido o intervalo entre as palestras n vale colocar não.

4 - Diria que a vinheta é pra ser exibida nos intervalos que as palestras não tiver conteúdo sendo exibido, é nosso conteúdo de fundo padrão. Por exemplo, ele também vai ser exibido no coffee break. Eu acho que deveríamos pensar em exibir o vídeo entre as palestras e fazer de fato os palestrantes respeitarem esse intervalo, darem um tempinho pras pessoas se realocarem de espaço, tomarem uma água, etc. Pra fins de nossa organização, esse intervalo deveria existir.

>  Adicionar brindes ou produtos nas sacolas dos participantes - Ana comentou que seria encher linguiça pq as empresas já sabem que podem fazer isso, mas acham válido colocar pra informar empresas que estejam patrocinando a primeira vez?

> Acho válido colocar tbm, qualquer pessoa ficaria curiosa com os brindes nas sacolas, incentivar a ter isso acho uma boa

5 - Acho que podemos deixar essa questão de informar sobre brindes e sorteios, e seria legal determinar uma faixa de tempo pra cada um fazer isso. Tipo 2 min pra interação com plateia no encerramento e na abertura. Tem empresas que pesam um pouco a mão nessas interações de sorteio, enquanto outras sequer pensam em usar esse tempo pra marketing. Acho que isso sim pode ser suuuper interessante colocar;

> Desconto em ingressos adicionais, isso seria referente ao preço do ingresso vigente na data certo?

6 - Concordo com a ideia

> Sobre os vídeos do intervalo pre e pós almoço, penso que tem muita repetição. Eu diminuiria pra 8, 6, 4 e 2 (contando com bronze)

7 - Eu diminuiria pra 4,3,2,1, porque vocês estão esquecendo que existe a possibilidade de ter n patrocinadores em cada cota :D

> Alias, outro ponto, o numero de ingressos cortesia por patrocinador tem alguma logica? 15, 7,4,3?

8 - Eu mudaria pra 11, 7, 4, 2, parece mais proporcional às cotas. Além disso, lembrar que podemos ter n patrocinadores pra cada cota.

**Comment by anadulce** [comment]
> Adicionado coleta de dados com QRCode pra todos
Eu acho que a gente não consegue controlar quem lê os QRCodes, então já era

> Vinheta entre palestras
Eu acho que temos que ter vinhetas entre palestras, o conteúdo que será exibido pode ser discutido, mas eu não vejo porque não ser esse conteúdo.

> Aqui minha sugestão é colocarmos quais emails, ex (Parágrafo nos e-mails de newsletter (confirmação de inscrição, aviso de tutoriais, etc)
Acho muita granularidade

> Definir limite para sorteio de brindes pra cada cota
Eu colocaria limite de tempo no palco para interações com participantes. 2-3 min
Podemos definir momentos pra isso, tipo no encerramento ou antes das LTs.

**Comment by belaaiza** [comment]
Quais vocês gostaram mais?

1. Cinzinha

<img width="1226" alt="Captura de Tela 2024-11-11 às 18 58 19" src="https://github.com/user-attachments/assets/7d34802d-4c4d-43c1-b113-259c54fbda74">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 58 30" src="https://github.com/user-attachments/assets/0aaea65d-1c04-4224-8dd0-965526404db0">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 58 34" src="https://github.com/user-attachments/assets/ec35e1dd-074c-4358-baec-de4b91032d70">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 58 39" src="https://github.com/user-attachments/assets/5dbda233-e6fe-4599-8d03-73ffc321119e">

2. Preto e Vermelho

<img width="1226" alt="Captura de Tela 2024-11-11 às 18 58 48" src="https://github.com/user-attachments/assets/98320ea8-40b0-4efe-b03e-f71d593b00b9">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 59 22" src="https://github.com/user-attachments/assets/4c8b2a59-71a5-4f6d-83ea-bfd3c0f93b5a">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 59 27" src="https://github.com/user-attachments/assets/f319c98c-1cb2-4947-93fc-03edfc339aaf">
<img width="1226" alt="Captura de Tela 2024-11-11 às 18 59 36" src="https://github.com/user-attachments/assets/06b14a4d-90f8-448d-9321-f71a32c5298b">

**Comment by belaaiza** [comment]
No telegram foi sugerido usar as cores/fonte do cinza com as cobras do vermelho. Primeira versão finalizada feita com essa sugestão, aguardando revisão para fecharmos a issue.

[Plano de Patrocínio v0.pdf](https://github.com/user-attachments/files/17911427/Plano.de.Patrocinio.v0.pdf)

**Comment by belaaiza** [comment]
Versão final revisada, com isso fechamos a issue.

[Plano de Patrocínio v0 (2).pdf](https://github.com/user-attachments/files/18013551/Plano.de.Patrocinio.v0.2.pdf)
