### ISSUE TITLE
Pagamento de acessoria jurídica para revisão do contrato do local

### ISSUE THREAD

**Issue by renan-asantos** [pythonbrasil/pybr2025-org#44]
Issue para acompanhar o pagamento do serviço de acessoria jurídica para revisão do contrato do local do evento (Centro de Eventos São Luís)

**Comment by renan-asantos** [comment]
@anicelysantos @cecivieira @tiidadavena @naanadr

Na última quinta-feira (04/12) a @anadulce preencheu o formulário de solicitação de pagamento referente ao serviço de revisão contratual do local do evento. Esse serviço foi oferecido pelo Bruno (advogado da APyB também).

Além do próprio preenchimento do formulário, estou marcando vocês para notificar que o **vencimento** do boleto é **amanhã dia 10/12 no valor de R$3000**

**Comment by anadulce** [comment]
@cecivieira @anicelysantos 
Este contrato tem vencimento previsto para hoje, poderiam priorizá-lo, por favor?
É um pagamento por boleto, e isso implica **multa em caso de atraso**.

**Comment by renan-asantos** [comment]
Pagamento realizado no dia 10/10, segundo email de resposta da APyB
